# Generated by Django 5.2.18 on 2026-10-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50, unique=True)),
                ('user_id', models.IntegerField()),
                ('payment_id', models.CharField(max_length=50)),
                ('card_id', models.IntegerField()),
                ('card_last_four', models.CharField(max_length=4)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
    ]
