# Generated by Django 5.2.18 on 2026-10-08 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit'), ('Premium', 'Premium')], default='Credit', max_length=20)),
                ('card_holder', models.CharField(max_length=100)),
                ('masked_number', models.CharField(max_length=19)),
                ('last_four', models.CharField(max_length=4)),
                ('expiry', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
